### ISSUE TITLE
Library versioning

### ISSUE THREAD

**Issue by clelange** [cms-cat/cmsstyle#25]
https://github.com/cms-cat/cmsstyle/blob/master/pyproject.toml#L7 points to `src/cmsstyle/_version.py` but that file doesn't exist. Should it be created and then we need to run a script (bump version) whenever we want to update?

**Comment by ttedeschi** [comment]
Assigning @andrzejnovak since he setup the full PyPi workflow

**Comment by andrzejnovak** [comment]
@clelange the file gets created in the release action automatically based on the release/tag name 

Check https://pypi.org/project/cmsstyle/#history
