### ISSUE TITLE
Definition of cms_lumi

### ISSUE THREAD

**Issue by pfs** [cms-cat/cmsstyle#26]
Hi,
thanks a lot for the tool. Can the following lines be changed?

https://github.com/cms-cat/cmsstyle/blob/bca5c248fb5d6a349aaf4c344ac21a0c3ab7f54b/src/cmsstyle/cmsstyle.py#L22-L26

the user may want to force a different unit (1/pb 1/nb, whatever) depending on the dataset being analyzed. S.th. like

```
if type(lumi)==float: 
        cms_lumi = f"{lumi:.0f}" if round_lumi else f"{lumi}"
        cms_lumi += " fb^{#minus1}"
elif type(lumi)==str:
        cms_lumi=lumi
```

thanks

**Comment by clelange** [comment]
Hi @pfs -- thanks for the feedback. This is certainly something that should be fixed. Please have a look at the proposed solution in #27 and let me know if that addresses your use cases.

**Comment by clelange** [comment]
v0.2.0 should show on PyPI soon and will have this change implemented.
