### ISSUE TITLE
Make CMS label requirements consistent between CAT docs and twiki

### ISSUE THREAD

**Issue by reimersa** [cms-cat/cmsstyle#37]
The CMS label requirements in the [CAT docs](https://cms-analysis.docs.cern.ch/guidelines/plotting/general/#labeling-guidelines) and [tutorial](https://github.com/ttedeschi/tutorial_CAT/blob/main/1-tutorial_CAT_recommendations.ipynb) for thesis-endorsed work and other non-public work are inconsistent with the requirements on the [reference twiki page](https://twiki.cern.ch/twiki/bin/view/CMS/PhysicsApprovals#Student_presentations_of_unappro).

In the docs: 
- Thesis Endorsement Work: "CMS Work-in-Progress" or "CMS Simulation Work-in-Progress"
- Other Non-public Work: "CMS Private Work" or "CMS Simulation Private Work"

On the twiki:
- Thesis Endorsement Work: "CMS Work in progress" (no specific mention of "CMS Simulation Work in progress")
- Other Non-public Work: "Private work (CMS data/simulation)”, "Private work (CMS data)” or "Private work (CMS simulation)"

**Comment by ttedeschi** [comment]
Implemented in https://gitlab.cern.ch/cms-analysis/docs/-/commit/fc81bc4b9f0eea939d04fed822ec21eb82749630
