### ISSUE TITLE
Name colors

### ISSUE THREAD

**Issue by lenzip** [cms-cat/cmsstyle#38]
Is it possible to name colors corresponding to the Petrof hex codes (e.g. `kCMSGreen` or `CMS.kGreen` something like that), so that these colors become available when importing cmsstyle?

**Comment by ttedeschi** [comment]
Since we have three different set of Petroff colors (which have no hex code in common), how would you suggest to identify them?
```
petroff_6 = ["#5790fc", "#f89c20", "#e42536", "#964a8b", "#9c9ca1", "#7a21dd"]
petroff_8 = ["#1845fb", "#ff5e02", "#c91f16", "#c849a9", "#adad7d", "#86c8dd", "#578dff", "#656364"]
petroff_10 = ["#3f90da", "#ffa90e", "#bd1f01", "#94a4a2", "#832db6", "#a96b59", "#e76300", "#b9ac70", "#717581", "#92dadd"]
```

**Comment by lenzip** [comment]
How about something like `CMS.p6.kGreen`, with `p6`, `p8` and `p10` identifying the palettes with 6, 8 and 10 colors respectively?

**Comment by ttedeschi** [comment]
Ok, addressed here https://github.com/cms-cat/cmsstyle/pull/40, specifically here https://github.com/cms-cat/cmsstyle/pull/40/commits/86e48a1052648a66203e12082b552001e30be6d7

**Comment by ttedeschi** [comment]
https://github.com/cms-cat/cmsstyle/pull/40 was merged, closing
