### ISSUE TITLE
avoid setting ROOT in batch mode

### ISSUE THREAD

**Issue by lenzip** [cms-cat/cmsstyle#42]
Dmytro Kovalskyi reported `cmsstyle` sets `rt.gROOT.SetBatch(rt.kTRUE)`. It would be better to avoid that. Not necessarly one wants to work in batch mode with `cmsstyle`.

**Comment by anmalara** [comment]
I think I disagree on this point. There is no need to run in iterative mode when producing plots. It is actually much more slower. And in any case one can unset it manually if needed.

**Comment by lenzip** [comment]
Well, likewise one can set it manually if needed, like I did in my PR. I think we should do least unexpected global changes as possible.

**Comment by ttedeschi** [comment]
Solved by https://github.com/cms-cat/cmsstyle/pull/43
